GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO quickbyte_user;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO quickbyte_user;
GRANT USAGE, CREATE ON SCHEMA public TO quickbyte_user;