--
-- PostgreSQL database dump
--

\restrict gzY25JSVZZ7IeRIopAthcQ3sNnnPnK0uOpbHi3ZkaTt7B8y65MaVL1UekLc1gm8

-- Dumped from database version 18.3
-- Dumped by pg_dump version 18.3

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: cart_addons; Type: TABLE; Schema: public; Owner: quickbyte_user
--

CREATE TABLE public.cart_addons (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    addon_name character varying(100) NOT NULL,
    addon_price numeric(10,2) NOT NULL,
    cart_item_id bigint NOT NULL,
    food_addon_id bigint NOT NULL
);


ALTER TABLE public.cart_addons OWNER TO quickbyte_user;

--
-- Name: cart_addons_id_seq; Type: SEQUENCE; Schema: public; Owner: quickbyte_user
--

ALTER TABLE public.cart_addons ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cart_addons_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cart_items; Type: TABLE; Schema: public; Owner: quickbyte_user
--

CREATE TABLE public.cart_items (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    quantity integer NOT NULL,
    total_price numeric(10,2) NOT NULL,
    unit_price numeric(10,2) NOT NULL,
    cart_id bigint NOT NULL,
    food_id bigint NOT NULL,
    variant_id bigint NOT NULL
);


ALTER TABLE public.cart_items OWNER TO quickbyte_user;

--
-- Name: cart_items_id_seq; Type: SEQUENCE; Schema: public; Owner: quickbyte_user
--

ALTER TABLE public.cart_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cart_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: carts; Type: TABLE; Schema: public; Owner: quickbyte_user
--

CREATE TABLE public.carts (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    total_amount numeric(12,2) NOT NULL,
    total_items integer NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.carts OWNER TO quickbyte_user;

--
-- Name: carts_id_seq; Type: SEQUENCE; Schema: public; Owner: quickbyte_user
--

ALTER TABLE public.carts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.carts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: categories; Type: TABLE; Schema: public; Owner: quickbyte_user
--

CREATE TABLE public.categories (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    description character varying(500),
    display_order integer NOT NULL,
    name character varying(100) NOT NULL,
    status character varying(30) NOT NULL,
    restaurant_id bigint NOT NULL,
    CONSTRAINT categories_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'INACTIVE'::character varying])::text[])))
);


ALTER TABLE public.categories OWNER TO quickbyte_user;

--
-- Name: categories_id_seq; Type: SEQUENCE; Schema: public; Owner: quickbyte_user
--

ALTER TABLE public.categories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.categories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: coupons; Type: TABLE; Schema: public; Owner: quickbyte_user
--

CREATE TABLE public.coupons (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    coupon_code character varying(30) NOT NULL,
    coupon_type character varying(255) NOT NULL,
    description character varying(500),
    discount_value numeric(10,2) NOT NULL,
    expiry_date date NOT NULL,
    maximum_discount numeric(10,2),
    minimum_order_amount numeric(10,2) NOT NULL,
    status character varying(255) NOT NULL,
    title character varying(150) NOT NULL,
    usage_limit integer NOT NULL,
    used_count integer NOT NULL,
    CONSTRAINT coupons_coupon_type_check CHECK (((coupon_type)::text = ANY ((ARRAY['PERCENTAGE'::character varying, 'FLAT'::character varying])::text[]))),
    CONSTRAINT coupons_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'INACTIVE'::character varying, 'EXPIRED'::character varying])::text[])))
);


ALTER TABLE public.coupons OWNER TO quickbyte_user;

--
-- Name: coupons_id_seq; Type: SEQUENCE; Schema: public; Owner: quickbyte_user
--

ALTER TABLE public.coupons ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.coupons_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: delivery_partners; Type: TABLE; Schema: public; Owner: quickbyte_user
--

CREATE TABLE public.delivery_partners (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    available boolean NOT NULL,
    delivery_status character varying(255) NOT NULL,
    name character varying(100) NOT NULL,
    phone_number character varying(15) NOT NULL,
    order_id bigint,
    CONSTRAINT delivery_partners_delivery_status_check CHECK (((delivery_status)::text = ANY ((ARRAY['AVAILABLE'::character varying, 'ASSIGNED'::character varying, 'PICKED_UP'::character varying, 'ON_THE_WAY'::character varying, 'DELIVERED'::character varying])::text[])))
);


ALTER TABLE public.delivery_partners OWNER TO quickbyte_user;

--
-- Name: delivery_partners_id_seq; Type: SEQUENCE; Schema: public; Owner: quickbyte_user
--

ALTER TABLE public.delivery_partners ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.delivery_partners_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: food_addons; Type: TABLE; Schema: public; Owner: quickbyte_user
--

CREATE TABLE public.food_addons (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    available boolean NOT NULL,
    display_order integer NOT NULL,
    name character varying(100) NOT NULL,
    price numeric(10,2) NOT NULL,
    food_id bigint NOT NULL
);


ALTER TABLE public.food_addons OWNER TO quickbyte_user;

--
-- Name: food_addons_id_seq; Type: SEQUENCE; Schema: public; Owner: quickbyte_user
--

ALTER TABLE public.food_addons ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.food_addons_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: food_images; Type: TABLE; Schema: public; Owner: quickbyte_user
--

CREATE TABLE public.food_images (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    display_order integer NOT NULL,
    image_url character varying(500) NOT NULL,
    thumbnail boolean NOT NULL,
    food_id bigint NOT NULL
);


ALTER TABLE public.food_images OWNER TO quickbyte_user;

--
-- Name: food_images_id_seq; Type: SEQUENCE; Schema: public; Owner: quickbyte_user
--

ALTER TABLE public.food_images ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.food_images_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: food_variants; Type: TABLE; Schema: public; Owner: quickbyte_user
--

CREATE TABLE public.food_variants (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    available boolean NOT NULL,
    price numeric(10,2) NOT NULL,
    stock integer NOT NULL,
    variant_type character varying(255) NOT NULL,
    food_id bigint NOT NULL,
    CONSTRAINT food_variants_variant_type_check CHECK (((variant_type)::text = ANY ((ARRAY['HALF'::character varying, 'FULL'::character varying, 'JUMBO'::character varying, 'FAMILY_PACK'::character varying])::text[])))
);


ALTER TABLE public.food_variants OWNER TO quickbyte_user;

--
-- Name: food_variants_id_seq; Type: SEQUENCE; Schema: public; Owner: quickbyte_user
--

ALTER TABLE public.food_variants ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.food_variants_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: foods; Type: TABLE; Schema: public; Owner: quickbyte_user
--

CREATE TABLE public.foods (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    average_rating double precision NOT NULL,
    best_seller boolean NOT NULL,
    description character varying(500) NOT NULL,
    food_type character varying(255) NOT NULL,
    name character varying(120) NOT NULL,
    preparation_time integer NOT NULL,
    price double precision NOT NULL,
    recommended boolean NOT NULL,
    status character varying(255) NOT NULL,
    total_reviews integer NOT NULL,
    category_id bigint NOT NULL,
    CONSTRAINT foods_food_type_check CHECK (((food_type)::text = ANY ((ARRAY['VEG'::character varying, 'NON_VEG'::character varying, 'EGG'::character varying])::text[]))),
    CONSTRAINT foods_status_check CHECK (((status)::text = ANY ((ARRAY['AVAILABLE'::character varying, 'OUT_OF_STOCK'::character varying, 'DISCONTINUED'::character varying])::text[])))
);


ALTER TABLE public.foods OWNER TO quickbyte_user;

--
-- Name: foods_id_seq; Type: SEQUENCE; Schema: public; Owner: quickbyte_user
--

ALTER TABLE public.foods ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.foods_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: order_addresses; Type: TABLE; Schema: public; Owner: quickbyte_user
--

CREATE TABLE public.order_addresses (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    area character varying(255) NOT NULL,
    city character varying(255) NOT NULL,
    country character varying(255) NOT NULL,
    district character varying(255) NOT NULL,
    landmark character varying(255),
    latitude double precision NOT NULL,
    longitude double precision NOT NULL,
    pincode character varying(255) NOT NULL,
    state character varying(255) NOT NULL,
    street character varying(255) NOT NULL,
    order_id bigint NOT NULL
);


ALTER TABLE public.order_addresses OWNER TO quickbyte_user;

--
-- Name: order_addresses_id_seq; Type: SEQUENCE; Schema: public; Owner: quickbyte_user
--

ALTER TABLE public.order_addresses ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.order_addresses_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: order_items; Type: TABLE; Schema: public; Owner: quickbyte_user
--

CREATE TABLE public.order_items (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    quantity integer NOT NULL,
    total_price numeric(10,2) NOT NULL,
    unit_price numeric(10,2) NOT NULL,
    food_id bigint NOT NULL,
    order_id bigint NOT NULL,
    variant_id bigint NOT NULL
);


ALTER TABLE public.order_items OWNER TO quickbyte_user;

--
-- Name: order_items_id_seq; Type: SEQUENCE; Schema: public; Owner: quickbyte_user
--

ALTER TABLE public.order_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.order_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: orders; Type: TABLE; Schema: public; Owner: quickbyte_user
--

CREATE TABLE public.orders (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    delivery_charge numeric(10,2) NOT NULL,
    grand_total numeric(10,2) NOT NULL,
    notes character varying(500),
    order_status character varying(255) NOT NULL,
    payment_status character varying(255) NOT NULL,
    sub_total numeric(10,2) NOT NULL,
    tax numeric(10,2) NOT NULL,
    customer_id bigint NOT NULL,
    restaurant_id bigint NOT NULL,
    CONSTRAINT orders_order_status_check CHECK (((order_status)::text = ANY ((ARRAY['PENDING'::character varying, 'CONFIRMED'::character varying, 'PREPARING'::character varying, 'READY_FOR_PICKUP'::character varying, 'OUT_FOR_DELIVERY'::character varying, 'DELIVERED'::character varying, 'CANCELLED'::character varying])::text[]))),
    CONSTRAINT orders_payment_status_check CHECK (((payment_status)::text = ANY ((ARRAY['PENDING'::character varying, 'SUCCESS'::character varying, 'FAILED'::character varying, 'REFUNDED'::character varying])::text[])))
);


ALTER TABLE public.orders OWNER TO quickbyte_user;

--
-- Name: orders_id_seq; Type: SEQUENCE; Schema: public; Owner: quickbyte_user
--

ALTER TABLE public.orders ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.orders_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: otp_verifications; Type: TABLE; Schema: public; Owner: quickbyte_user
--

CREATE TABLE public.otp_verifications (
    id bigint NOT NULL,
    email character varying(255) NOT NULL,
    expires_at timestamp(6) without time zone NOT NULL,
    otp character varying(255) NOT NULL,
    verified boolean NOT NULL
);


ALTER TABLE public.otp_verifications OWNER TO quickbyte_user;

--
-- Name: otp_verifications_id_seq; Type: SEQUENCE; Schema: public; Owner: quickbyte_user
--

ALTER TABLE public.otp_verifications ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.otp_verifications_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: payments; Type: TABLE; Schema: public; Owner: quickbyte_user
--

CREATE TABLE public.payments (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    amount numeric(10,2) NOT NULL,
    failure_reason character varying(500),
    gateway_order_id character varying(150),
    gateway_payment_id character varying(150),
    payment_method character varying(255) NOT NULL,
    payment_status character varying(255) NOT NULL,
    transaction_id character varying(150),
    order_id bigint NOT NULL,
    CONSTRAINT payments_payment_method_check CHECK (((payment_method)::text = ANY ((ARRAY['CASH_ON_DELIVERY'::character varying, 'UPI'::character varying, 'CREDIT_CARD'::character varying, 'DEBIT_CARD'::character varying, 'NET_BANKING'::character varying, 'WALLET'::character varying])::text[]))),
    CONSTRAINT payments_payment_status_check CHECK (((payment_status)::text = ANY ((ARRAY['PENDING'::character varying, 'SUCCESS'::character varying, 'FAILED'::character varying, 'REFUNDED'::character varying])::text[])))
);


ALTER TABLE public.payments OWNER TO quickbyte_user;

--
-- Name: payments_id_seq; Type: SEQUENCE; Schema: public; Owner: quickbyte_user
--

ALTER TABLE public.payments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.payments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: refresh_tokens; Type: TABLE; Schema: public; Owner: quickbyte_user
--

CREATE TABLE public.refresh_tokens (
    id bigint NOT NULL,
    expiry_date timestamp(6) without time zone NOT NULL,
    token character varying(500) NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.refresh_tokens OWNER TO quickbyte_user;

--
-- Name: refresh_tokens_id_seq; Type: SEQUENCE; Schema: public; Owner: quickbyte_user
--

ALTER TABLE public.refresh_tokens ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.refresh_tokens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: restaurant_addresses; Type: TABLE; Schema: public; Owner: quickbyte_user
--

CREATE TABLE public.restaurant_addresses (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    area character varying(255) NOT NULL,
    city character varying(255) NOT NULL,
    country character varying(255) NOT NULL,
    district character varying(255) NOT NULL,
    landmark character varying(255),
    latitude double precision NOT NULL,
    longitude double precision NOT NULL,
    pincode character varying(10) NOT NULL,
    state character varying(255) NOT NULL,
    street character varying(255) NOT NULL,
    restaurant_id bigint NOT NULL
);


ALTER TABLE public.restaurant_addresses OWNER TO quickbyte_user;

--
-- Name: restaurant_addresses_id_seq; Type: SEQUENCE; Schema: public; Owner: quickbyte_user
--

ALTER TABLE public.restaurant_addresses ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.restaurant_addresses_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: restaurant_images; Type: TABLE; Schema: public; Owner: quickbyte_user
--

CREATE TABLE public.restaurant_images (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    display_order integer NOT NULL,
    image_url character varying(500) NOT NULL,
    thumbnail boolean NOT NULL,
    restaurant_id bigint NOT NULL
);


ALTER TABLE public.restaurant_images OWNER TO quickbyte_user;

--
-- Name: restaurant_images_id_seq; Type: SEQUENCE; Schema: public; Owner: quickbyte_user
--

ALTER TABLE public.restaurant_images ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.restaurant_images_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: restaurant_timings; Type: TABLE; Schema: public; Owner: quickbyte_user
--

CREATE TABLE public.restaurant_timings (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    closed boolean NOT NULL,
    closing_time time(6) without time zone NOT NULL,
    day_of_week character varying(255) NOT NULL,
    opening_time time(6) without time zone NOT NULL,
    restaurant_id bigint NOT NULL,
    CONSTRAINT restaurant_timings_day_of_week_check CHECK (((day_of_week)::text = ANY ((ARRAY['MONDAY'::character varying, 'TUESDAY'::character varying, 'WEDNESDAY'::character varying, 'THURSDAY'::character varying, 'FRIDAY'::character varying, 'SATURDAY'::character varying, 'SUNDAY'::character varying])::text[])))
);


ALTER TABLE public.restaurant_timings OWNER TO quickbyte_user;

--
-- Name: restaurant_timings_id_seq; Type: SEQUENCE; Schema: public; Owner: quickbyte_user
--

ALTER TABLE public.restaurant_timings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.restaurant_timings_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: restaurants; Type: TABLE; Schema: public; Owner: quickbyte_user
--

CREATE TABLE public.restaurants (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    description character varying(500) NOT NULL,
    email character varying(100) NOT NULL,
    name character varying(100) NOT NULL,
    phone_number character varying(15) NOT NULL,
    status character varying(255) NOT NULL,
    owner_id bigint NOT NULL,
    CONSTRAINT restaurants_status_check CHECK (((status)::text = ANY ((ARRAY['UNDER_VERIFICATION'::character varying, 'ACTIVE'::character varying, 'TEMPORARILY_CLOSED'::character varying, 'PERMANENTLY_CLOSED'::character varying, 'SUSPENDED'::character varying])::text[])))
);


ALTER TABLE public.restaurants OWNER TO quickbyte_user;

--
-- Name: restaurants_id_seq; Type: SEQUENCE; Schema: public; Owner: quickbyte_user
--

ALTER TABLE public.restaurants ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.restaurants_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: reviews; Type: TABLE; Schema: public; Owner: quickbyte_user
--

CREATE TABLE public.reviews (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    rating integer NOT NULL,
    review character varying(1000),
    customer_id bigint NOT NULL,
    food_id bigint NOT NULL,
    restaurant_id bigint NOT NULL
);


ALTER TABLE public.reviews OWNER TO quickbyte_user;

--
-- Name: reviews_id_seq; Type: SEQUENCE; Schema: public; Owner: quickbyte_user
--

ALTER TABLE public.reviews ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reviews_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: quickbyte_user
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    account_status character varying(255) NOT NULL,
    email character varying(255) NOT NULL,
    full_name character varying(100) NOT NULL,
    password character varying(255) NOT NULL,
    phone_number character varying(255) NOT NULL,
    role character varying(30) NOT NULL,
    CONSTRAINT users_account_status_check CHECK (((account_status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'INACTIVE'::character varying, 'BLOCKED'::character varying])::text[]))),
    CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['ADMIN'::character varying, 'CUSTOMER'::character varying, 'RESTAURANT_OWNER'::character varying, 'DELIVERY_PARTNER'::character varying])::text[])))
);


ALTER TABLE public.users OWNER TO quickbyte_user;

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: quickbyte_user
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: cart_addons; Type: TABLE DATA; Schema: public; Owner: quickbyte_user
--

COPY public.cart_addons (id, created_at, updated_at, addon_name, addon_price, cart_item_id, food_addon_id) FROM stdin;
\.


--
-- Data for Name: cart_items; Type: TABLE DATA; Schema: public; Owner: quickbyte_user
--

COPY public.cart_items (id, created_at, updated_at, quantity, total_price, unit_price, cart_id, food_id, variant_id) FROM stdin;
\.


--
-- Data for Name: carts; Type: TABLE DATA; Schema: public; Owner: quickbyte_user
--

COPY public.carts (id, created_at, updated_at, total_amount, total_items, user_id) FROM stdin;
1	2026-09-06 12:57:43.123119	2026-09-06 21:35:46.2941	0.00	0	1
\.


--
-- Data for Name: categories; Type: TABLE DATA; Schema: public; Owner: quickbyte_user
--

COPY public.categories (id, created_at, updated_at, description, display_order, name, status, restaurant_id) FROM stdin;
1	2026-09-06 12:15:33.886463	2026-09-06 12:15:33.886463	Are you like starters, then this is your exact spot to come and explore.	1	Starters	ACTIVE	1
2	2026-09-06 12:17:21.953013	2026-09-06 12:17:32.762338	All kind of Juices and Icecreams available here....	1	Juice & Beverages	ACTIVE	1
3	2026-09-06 12:45:42.340488	2026-09-06 12:45:42.340488	Delicious Items are available here for you guys.....	1	Main Course	ACTIVE	2
4	2026-09-06 12:46:38.427035	2026-09-06 12:46:38.427035	Desserts lovers love this restaurant and won't forget it....	1	Desserts	ACTIVE	2
\.


--
-- Data for Name: coupons; Type: TABLE DATA; Schema: public; Owner: quickbyte_user
--

COPY public.coupons (id, created_at, updated_at, coupon_code, coupon_type, description, discount_value, expiry_date, maximum_discount, minimum_order_amount, status, title, usage_limit, used_count) FROM stdin;
\.


--
-- Data for Name: delivery_partners; Type: TABLE DATA; Schema: public; Owner: quickbyte_user
--

COPY public.delivery_partners (id, created_at, updated_at, available, delivery_status, name, phone_number, order_id) FROM stdin;
1	2026-09-06 17:15:31.410824	2026-09-06 17:17:30.589254	f	ASSIGNED	Harshat hussain	9219670280	1
2	2026-09-06 17:16:08.707514	2026-09-06 21:29:46.603184	f	ASSIGNED	Manoj	9219670281	6
3	2026-09-06 17:46:48.113323	2026-09-06 21:37:11.020086	f	ASSIGNED	Logesh	9819670281	7
5	2026-09-06 21:38:00.261109	2026-09-06 21:38:00.261109	t	ASSIGNED	Karthik	9205347797	\N
4	2026-09-06 17:48:27.790474	2026-09-06 21:41:48.10804	t	AVAILABLE	Logesh	9205346297	\N
\.


--
-- Data for Name: food_addons; Type: TABLE DATA; Schema: public; Owner: quickbyte_user
--

COPY public.food_addons (id, created_at, updated_at, available, display_order, name, price, food_id) FROM stdin;
1	2026-09-06 12:23:17.130675	2026-09-06 12:23:17.130675	t	1	One more Cup	10.00	1
2	2026-09-06 12:23:46.747271	2026-09-06 12:23:46.747271	t	1	Extra Chicken	50.00	3
3	2026-09-06 12:24:01.505317	2026-09-06 12:24:01.505317	t	1	Extra Mutton 	80.00	2
4	2026-09-06 12:51:41.712958	2026-09-06 12:51:41.712958	t	1	Need one  more cup	10.00	7
5	2026-09-06 12:51:53.800803	2026-09-06 12:51:53.800803	t	1	Need Extra	20.00	6
\.


--
-- Data for Name: food_images; Type: TABLE DATA; Schema: public; Owner: quickbyte_user
--

COPY public.food_images (id, created_at, updated_at, display_order, image_url, thumbnail, food_id) FROM stdin;
1	2026-09-06 14:07:07.556903	2026-09-06 14:07:07.556903	1	https://www.indianhealthyrecipes.com/wp-content/uploads/2022/03/chicken-65-restaurant-style.jpg	t	3
2	2026-09-06 14:10:51.310366	2026-09-06 14:10:51.310366	1	https://cdn.loveandlemons.com/wp-content/uploads/2023/06/homemade-ice-cream-recipe.jpg	t	6
3	2026-09-06 14:12:15.247679	2026-09-06 14:12:15.247679	1	https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTZARE--TFYjNmQPVz71A6hu7HKZJLmSJX5awSmm00F_25gqfCDdYpQdtud&s=10	t	7
4	2026-09-06 14:12:57.306204	2026-09-06 14:12:57.306204	1	https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRzXcKuQ1Tco8UHqpF-wclYKPnnATwJM-srPqPkWArdxg&s=10	t	1
5	2026-09-06 14:13:40.70853	2026-09-06 14:13:40.70853	1	https://sinfullyspicy.com/wp-content/uploads/2024/09/1200-by-1200-images-1.jpg	t	2
6	2026-09-06 14:14:30.266295	2026-09-06 14:14:30.266295	1	https://images.pexels.com/photos/16020573/pexels-photo-16020573/free-photo-of-rice-and-chicken-meal-on-the-plate.jpeg	t	4
7	2026-09-06 14:15:12.543496	2026-09-06 14:15:12.543496	1	https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT5qMVg6jPhoBo3zLih7KTaEvc9zWjLmQtUjg9ak_Vyi6mpclCmH80_ithG&s=10	t	5
\.


--
-- Data for Name: food_variants; Type: TABLE DATA; Schema: public; Owner: quickbyte_user
--

COPY public.food_variants (id, created_at, updated_at, available, price, stock, variant_type, food_id) FROM stdin;
1	2026-09-06 12:21:12.187009	2026-09-06 12:21:12.187009	t	80.00	3	FULL	1
2	2026-09-06 12:21:31.407818	2026-09-06 12:21:31.407818	t	180.00	5	HALF	3
3	2026-09-06 12:21:45.136633	2026-09-06 12:21:45.136633	t	320.00	3	FULL	2
4	2026-09-06 12:21:57.905807	2026-09-06 12:21:57.905807	t	499.00	2	FAMILY_PACK	2
5	2026-09-06 12:22:15.206266	2026-09-06 12:22:15.206266	t	400.00	1	JUMBO	3
6	2026-09-06 12:50:06.512196	2026-09-06 12:50:06.512196	t	80.00	3	HALF	7
7	2026-09-06 12:50:19.467687	2026-09-06 12:50:19.467687	t	150.00	5	FULL	7
8	2026-09-06 12:50:27.574327	2026-09-06 12:50:27.574327	t	80.00	3	HALF	6
9	2026-09-06 12:50:39.627523	2026-09-06 12:50:39.627523	t	300.00	1	FAMILY_PACK	6
10	2026-09-06 12:50:53.549959	2026-09-06 12:50:53.549959	t	160.00	2	HALF	4
11	2026-09-06 12:51:03.683328	2026-09-06 12:51:03.683328	t	250.00	2	JUMBO	4
12	2026-09-06 12:51:12.690811	2026-09-06 12:51:12.690811	t	200.00	4	FULL	5
\.


--
-- Data for Name: foods; Type: TABLE DATA; Schema: public; Owner: quickbyte_user
--

COPY public.foods (id, created_at, updated_at, average_rating, best_seller, description, food_type, name, preparation_time, price, recommended, status, total_reviews, category_id) FROM stdin;
1	2026-09-06 12:19:03.874991	2026-09-06 12:19:03.874991	0	f	we have  all types of Milk shakes ( non-alcoholic and alcoholic )...	VEG	Mil Shake	25	80	t	AVAILABLE	0	2
2	2026-09-06 12:20:13.619184	2026-09-06 12:20:13.619184	0	t	Any Non-veg Lovers!!!!.... here is your Restaurant to explore	NON_VEG	Mutton Fry	45	299.85	t	AVAILABLE	0	1
3	2026-09-06 12:20:45.667646	2026-09-06 12:20:45.667646	0	t	Any Non-veg Lovers!!!!.... here is your Restaurant to explore....	NON_VEG	Chicken 65	40	250	t	AVAILABLE	0	1
4	2026-09-06 12:47:17.153359	2026-09-06 12:47:17.153359	0	t	All Biryani will be available here	NON_VEG	Biryani	50	250	t	AVAILABLE	0	3
5	2026-09-06 12:48:05.415018	2026-09-06 12:48:05.415018	0	f	Both Veg and Non-veg Rices are available here.	EGG	Fried Rice	45	200	t	AVAILABLE	0	3
6	2026-09-06 12:48:56.407475	2026-09-06 12:48:56.407475	0	t	Ice crean lovers assemble here	VEG	Vannila Ice cream	50	119.85	t	AVAILABLE	0	4
7	2026-09-06 12:49:34.384676	2026-09-06 12:49:34.384676	0	t	Salad's are special famous here	VEG	Friut Salad	25	150	f	AVAILABLE	0	4
\.


--
-- Data for Name: order_addresses; Type: TABLE DATA; Schema: public; Owner: quickbyte_user
--

COPY public.order_addresses (id, created_at, updated_at, area, city, country, district, landmark, latitude, longitude, pincode, state, street, order_id) FROM stdin;
1	2026-09-06 12:58:02.0532	2026-09-06 12:58:02.0532	N/A	Chennai	India	Chennai		13.0827	80.2707	600000	Tamil Nadu	noor complex chennai	1
2	2026-09-06 12:59:18.092552	2026-09-06 12:59:18.092552	N/A	Chennai	India	Chennai		13.0827	80.2707	600000	Tamil Nadu	cuddalore panruti	2
3	2026-09-06 13:00:01.912384	2026-09-06 13:00:01.912384	N/A	Chennai	India	Chennai		13.0827	80.2707	600000	Tamil Nadu	kilambakkam	3
4	2026-09-06 13:02:53.159206	2026-09-06 13:02:53.159206	N/A	Chennai	India	Chennai		13.0827	80.2707	600000	Tamil Nadu	noor mahal kumbakonam	4
5	2026-09-06 21:23:41.568296	2026-09-06 21:23:41.568296	N/A	Chennai	India	Chennai		13.0827	80.2707	600000	Tamil Nadu	noor mahal	5
6	2026-09-06 21:27:28.595791	2026-09-06 21:27:28.596889	N/A	Chennai	India	Chennai		13.0827	80.2707	600000	Tamil Nadu	noor mahal	6
7	2026-09-06 21:35:46.267084	2026-09-06 21:35:46.267084	N/A	Chennai	India	Chennai		13.0827	80.2707	600000	Tamil Nadu	srinivasa complex	7
\.


--
-- Data for Name: order_items; Type: TABLE DATA; Schema: public; Owner: quickbyte_user
--

COPY public.order_items (id, created_at, updated_at, quantity, total_price, unit_price, food_id, order_id, variant_id) FROM stdin;
1	2026-09-06 12:58:02.062576	2026-09-06 12:58:02.062576	2	600.00	300.00	6	1	9
2	2026-09-06 12:59:18.094977	2026-09-06 12:59:18.094977	1	200.00	200.00	5	2	12
3	2026-09-06 13:00:01.91529	2026-09-06 13:00:01.91529	1	80.00	80.00	7	3	6
4	2026-09-06 13:02:53.161852	2026-09-06 13:02:53.161852	2	360.00	180.00	3	4	2
5	2026-09-06 21:23:41.574392	2026-09-06 21:23:41.574392	2	160.00	80.00	6	5	8
6	2026-09-06 21:27:28.601856	2026-09-06 21:27:28.601856	1	80.00	80.00	1	6	1
7	2026-09-06 21:35:46.273085	2026-09-06 21:35:46.27409	2	640.00	320.00	2	7	3
\.


--
-- Data for Name: orders; Type: TABLE DATA; Schema: public; Owner: quickbyte_user
--

COPY public.orders (id, created_at, updated_at, delivery_charge, grand_total, notes, order_status, payment_status, sub_total, tax, customer_id, restaurant_id) FROM stdin;
2	2026-09-06 12:59:18.088456	2026-09-06 12:59:20.131662	40.00	250.00	Payment Method: UPI	CONFIRMED	SUCCESS	200.00	10.00	1	2
3	2026-09-06 13:00:01.90739	2026-09-06 13:00:01.927683	40.00	124.00	Payment Method: CASH_ON_DELIVERY	PENDING	PENDING	80.00	4.00	1	2
1	2026-09-06 12:58:02.044433	2026-09-06 17:17:30.589254	40.00	670.00	Payment Method: CASH_ON_DELIVERY	OUT_FOR_DELIVERY	PENDING	600.00	30.00	1	2
5	2026-09-06 21:23:41.560393	2026-09-06 21:23:41.599275	40.00	208.00	Payment Method: CASH_ON_DELIVERY	PENDING	PENDING	160.00	8.00	1	2
6	2026-09-06 21:27:28.589729	2026-09-06 21:27:55.66594	40.00	124.00	Payment Method: UPI	READY_FOR_PICKUP	SUCCESS	80.00	4.00	1	1
7	2026-09-06 21:35:46.262085	2026-09-06 21:37:11.020086	40.00	712.00	Payment Method: CASH_ON_DELIVERY	OUT_FOR_DELIVERY	PENDING	640.00	32.00	1	1
4	2026-09-06 13:02:53.156296	2026-09-06 21:41:48.090219	40.00	418.00	Payment Method: UPI	DELIVERED	SUCCESS	360.00	18.00	1	1
\.


--
-- Data for Name: otp_verifications; Type: TABLE DATA; Schema: public; Owner: quickbyte_user
--

COPY public.otp_verifications (id, email, expires_at, otp, verified) FROM stdin;
\.


--
-- Data for Name: payments; Type: TABLE DATA; Schema: public; Owner: quickbyte_user
--

COPY public.payments (id, created_at, updated_at, amount, failure_reason, gateway_order_id, gateway_payment_id, payment_method, payment_status, transaction_id, order_id) FROM stdin;
1	2026-09-06 12:58:02.146925	2026-09-06 12:58:02.146925	670.00	\N	\N	\N	CASH_ON_DELIVERY	PENDING	\N	1
2	2026-09-06 12:59:18.150942	2026-09-06 12:59:20.131662	250.00	\N	\N	QB-PAY-1788679760100	UPI	SUCCESS	TXN-1788679760100	2
3	2026-09-06 13:00:01.968281	2026-09-06 13:00:01.968281	124.00	\N	\N	\N	CASH_ON_DELIVERY	PENDING	\N	3
4	2026-09-06 13:02:53.216622	2026-09-06 13:02:54.693302	418.00	\N	\N	QB-PAY-1788679974671	UPI	SUCCESS	TXN-1788679974671	4
5	2026-09-06 21:23:41.691373	2026-09-06 21:23:41.691373	208.00	\N	\N	\N	CASH_ON_DELIVERY	PENDING	\N	5
6	2026-09-06 21:27:28.684341	2026-09-06 21:27:30.997058	124.00	\N	\N	QB-PAY-1788710250951	UPI	SUCCESS	TXN-1788710250951	6
7	2026-09-06 21:35:46.396305	2026-09-06 21:35:46.396305	712.00	\N	\N	\N	CASH_ON_DELIVERY	PENDING	\N	7
\.


--
-- Data for Name: refresh_tokens; Type: TABLE DATA; Schema: public; Owner: quickbyte_user
--

COPY public.refresh_tokens (id, expiry_date, token, user_id) FROM stdin;
56	2026-09-13 18:00:37.367155	332fcf4c-8a69-4eba-9755-58b1b4c95ca0	4
35	2026-09-13 18:57:33.053306	bcb03a6f-1f5e-4d30-8862-836fd71c2497	3
51	2026-09-13 21:36:42.294879	6d5f5550-ecc9-443d-a3da-496f7150b51e	2
54	2026-09-13 21:42:12.176896	6f02f993-3a36-40d8-9b8e-902c8a9296c3	1
\.


--
-- Data for Name: restaurant_addresses; Type: TABLE DATA; Schema: public; Owner: quickbyte_user
--

COPY public.restaurant_addresses (id, created_at, updated_at, area, city, country, district, landmark, latitude, longitude, pincode, state, street, restaurant_id) FROM stdin;
1	2026-09-06 12:12:46.291654	2026-09-06 12:12:46.291654	Kelambakkam	panruti	India	cuddalore		28.9001	25.8786	607106	TAMILNADU	Noor complex chennai salai	1
2	2026-09-06 12:44:41.18325	2026-09-06 12:44:41.18325	kilambakkam	Cuddalore	India	Chengalpattu		29.9999	10.8776	607106	TAMILNADU	Noor complex chennai salai	2
\.


--
-- Data for Name: restaurant_images; Type: TABLE DATA; Schema: public; Owner: quickbyte_user
--

COPY public.restaurant_images (id, created_at, updated_at, display_order, image_url, thumbnail, restaurant_id) FROM stdin;
1	2026-09-06 12:25:24.857583	2026-09-06 12:25:24.857583	1	https://www.shutterstock.com/shutterstock/photos/2756252787/display_1500/stock-photo-a-diverse-group-of-people-enjoying-a-meal-at-a-wooden-table-sharing-various-dishes-like-burgers-2756252787.jpg	f	1
2	2026-09-06 12:37:40.07296	2026-09-06 12:37:40.07296	2	https://www.shutterstock.com/shutterstock/photos/2676167619/display_1500/stock-photo-wings-steaks-burgers-and-beer-on-a-table-at-a-sports-bar-do-not-crop-edges-of-the-food-2676167619.jpg	f	1
3	2026-09-06 12:52:24.092888	2026-09-06 12:52:24.092888	1	https://www.shutterstock.com/shutterstock/photos/2659975895/display_1500/stock-photo-food-and-drinks-assortment-of-dishes-from-different-countries-of-the-world-photo-collage-of-2659975895.jpg	f	2
4	2026-09-06 12:53:00.983474	2026-09-06 12:53:00.983474	2	https://www.shutterstock.com/shutterstock/photos/2794759763/display_1500/stock-photo-interior-of-a-traditional-central-javanese-restaurant-d-rendering-2794759763.jpg	f	2
\.


--
-- Data for Name: restaurant_timings; Type: TABLE DATA; Schema: public; Owner: quickbyte_user
--

COPY public.restaurant_timings (id, created_at, updated_at, closed, closing_time, day_of_week, opening_time, restaurant_id) FROM stdin;
2	2026-09-06 12:38:31.354097	2026-09-06 12:38:31.354097	t	00:00:00	SUNDAY	00:00:00	1
3	2026-09-06 12:38:50.06859	2026-09-06 12:38:50.06859	f	22:00:00	MONDAY	09:00:00	1
4	2026-09-06 12:53:08.442208	2026-09-06 12:53:08.442208	f	22:00:00	MONDAY	09:00:00	2
5	2026-09-06 12:53:12.351529	2026-09-06 12:53:12.352608	f	22:00:00	WEDNESDAY	09:00:00	2
6	2026-09-06 12:53:17.377817	2026-09-06 12:53:17.377817	t	00:00:00	SATURDAY	00:00:00	2
\.


--
-- Data for Name: restaurants; Type: TABLE DATA; Schema: public; Owner: quickbyte_user
--

COPY public.restaurants (id, created_at, updated_at, description, email, name, phone_number, status, owner_id) FROM stdin;
1	2026-09-06 12:12:46.276497	2026-09-06 12:14:26.370598	Try and Explore more delicious Foods here.	mahaboopsiddhiq@gmail.com	Siddhu's Restaurant	9344787657	UNDER_VERIFICATION	2
2	2026-09-06 12:44:41.179247	2026-09-06 12:44:54.129848	Delicious Foods are getting ready visit and Explore it!!!!!!!	katheejasid@gmail.com	Katheeja's Restaurant	9344787658	UNDER_VERIFICATION	3
\.


--
-- Data for Name: reviews; Type: TABLE DATA; Schema: public; Owner: quickbyte_user
--

COPY public.reviews (id, created_at, updated_at, rating, review, customer_id, food_id, restaurant_id) FROM stdin;
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: quickbyte_user
--

COPY public.users (id, created_at, updated_at, account_status, email, full_name, password, phone_number, role) FROM stdin;
1	2026-09-05 22:49:50.825965	2026-09-05 22:49:50.825965	ACTIVE	mahaboopsiddhi11@gmail.com	M Mahaboop Siddhik	$2a$10$3vuJ.5wKJCBtplqDx1VbjuxpUuMys0LEVhBHbL8kWdS08icXUVAh6	8777866568	CUSTOMER
2	2026-09-06 12:10:52.973292	2026-09-06 12:10:52.973292	ACTIVE	restaurantowner01@gmail.com	katheejaRestaurant	$2a$10$a5BAUWW/JKdYjWOgLdtBXe2siwA55okh2as4GLDLKQpkTe.FEYxPm	9344343434	RESTAURANT_OWNER
3	2026-09-06 12:42:21.752444	2026-09-06 12:42:21.752444	ACTIVE	restaurantowner02@gmail.com	siddhuKatheeja	$2a$10$FhklpkMZhjodJ2oimb9FAeALuquM888HqHekNQuLCY7scmTVWaYc.	9898876657	RESTAURANT_OWNER
4	2026-09-06 13:10:20.002148	2026-09-06 13:10:20.002148	ACTIVE	Siddadmin01@gmail.com	Rufaitha	$2a$10$QvYGVu4v1UMCBMv2L21ZU.x4yKd0UGjw9k.exquAvQLCDyJ48J.WW	7867922977	ADMIN
\.


--
-- Name: cart_addons_id_seq; Type: SEQUENCE SET; Schema: public; Owner: quickbyte_user
--

SELECT pg_catalog.setval('public.cart_addons_id_seq', 1, false);


--
-- Name: cart_items_id_seq; Type: SEQUENCE SET; Schema: public; Owner: quickbyte_user
--

SELECT pg_catalog.setval('public.cart_items_id_seq', 9, true);


--
-- Name: carts_id_seq; Type: SEQUENCE SET; Schema: public; Owner: quickbyte_user
--

SELECT pg_catalog.setval('public.carts_id_seq', 1, true);


--
-- Name: categories_id_seq; Type: SEQUENCE SET; Schema: public; Owner: quickbyte_user
--

SELECT pg_catalog.setval('public.categories_id_seq', 4, true);


--
-- Name: coupons_id_seq; Type: SEQUENCE SET; Schema: public; Owner: quickbyte_user
--

SELECT pg_catalog.setval('public.coupons_id_seq', 1, false);


--
-- Name: delivery_partners_id_seq; Type: SEQUENCE SET; Schema: public; Owner: quickbyte_user
--

SELECT pg_catalog.setval('public.delivery_partners_id_seq', 5, true);


--
-- Name: food_addons_id_seq; Type: SEQUENCE SET; Schema: public; Owner: quickbyte_user
--

SELECT pg_catalog.setval('public.food_addons_id_seq', 5, true);


--
-- Name: food_images_id_seq; Type: SEQUENCE SET; Schema: public; Owner: quickbyte_user
--

SELECT pg_catalog.setval('public.food_images_id_seq', 7, true);


--
-- Name: food_variants_id_seq; Type: SEQUENCE SET; Schema: public; Owner: quickbyte_user
--

SELECT pg_catalog.setval('public.food_variants_id_seq', 12, true);


--
-- Name: foods_id_seq; Type: SEQUENCE SET; Schema: public; Owner: quickbyte_user
--

SELECT pg_catalog.setval('public.foods_id_seq', 7, true);


--
-- Name: order_addresses_id_seq; Type: SEQUENCE SET; Schema: public; Owner: quickbyte_user
--

SELECT pg_catalog.setval('public.order_addresses_id_seq', 7, true);


--
-- Name: order_items_id_seq; Type: SEQUENCE SET; Schema: public; Owner: quickbyte_user
--

SELECT pg_catalog.setval('public.order_items_id_seq', 7, true);


--
-- Name: orders_id_seq; Type: SEQUENCE SET; Schema: public; Owner: quickbyte_user
--

SELECT pg_catalog.setval('public.orders_id_seq', 7, true);


--
-- Name: otp_verifications_id_seq; Type: SEQUENCE SET; Schema: public; Owner: quickbyte_user
--

SELECT pg_catalog.setval('public.otp_verifications_id_seq', 1, false);


--
-- Name: payments_id_seq; Type: SEQUENCE SET; Schema: public; Owner: quickbyte_user
--

SELECT pg_catalog.setval('public.payments_id_seq', 7, true);


--
-- Name: refresh_tokens_id_seq; Type: SEQUENCE SET; Schema: public; Owner: quickbyte_user
--

SELECT pg_catalog.setval('public.refresh_tokens_id_seq', 56, true);


--
-- Name: restaurant_addresses_id_seq; Type: SEQUENCE SET; Schema: public; Owner: quickbyte_user
--

SELECT pg_catalog.setval('public.restaurant_addresses_id_seq', 2, true);


--
-- Name: restaurant_images_id_seq; Type: SEQUENCE SET; Schema: public; Owner: quickbyte_user
--

SELECT pg_catalog.setval('public.restaurant_images_id_seq', 4, true);


--
-- Name: restaurant_timings_id_seq; Type: SEQUENCE SET; Schema: public; Owner: quickbyte_user
--

SELECT pg_catalog.setval('public.restaurant_timings_id_seq', 6, true);


--
-- Name: restaurants_id_seq; Type: SEQUENCE SET; Schema: public; Owner: quickbyte_user
--

SELECT pg_catalog.setval('public.restaurants_id_seq', 2, true);


--
-- Name: reviews_id_seq; Type: SEQUENCE SET; Schema: public; Owner: quickbyte_user
--

SELECT pg_catalog.setval('public.reviews_id_seq', 1, false);


--
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: quickbyte_user
--

SELECT pg_catalog.setval('public.users_id_seq', 4, true);


--
-- Name: cart_addons cart_addons_pkey; Type: CONSTRAINT; Schema: public; Owner: quickbyte_user
--

ALTER TABLE ONLY public.cart_addons
    ADD CONSTRAINT cart_addons_pkey PRIMARY KEY (id);


--
-- Name: cart_items cart_items_pkey; Type: CONSTRAINT; Schema: public; Owner: quickbyte_user
--

ALTER TABLE ONLY public.cart_items
    ADD CONSTRAINT cart_items_pkey PRIMARY KEY (id);


--
-- Name: carts carts_pkey; Type: CONSTRAINT; Schema: public; Owner: quickbyte_user
--

ALTER TABLE ONLY public.carts
    ADD CONSTRAINT carts_pkey PRIMARY KEY (id);


--
-- Name: categories categories_pkey; Type: CONSTRAINT; Schema: public; Owner: quickbyte_user
--

ALTER TABLE ONLY public.categories
    ADD CONSTRAINT categories_pkey PRIMARY KEY (id);


--
-- Name: coupons coupons_pkey; Type: CONSTRAINT; Schema: public; Owner: quickbyte_user
--

ALTER TABLE ONLY public.coupons
    ADD CONSTRAINT coupons_pkey PRIMARY KEY (id);


--
-- Name: delivery_partners delivery_partners_pkey; Type: CONSTRAINT; Schema: public; Owner: quickbyte_user
--

ALTER TABLE ONLY public.delivery_partners
    ADD CONSTRAINT delivery_partners_pkey PRIMARY KEY (id);


--
-- Name: food_addons food_addons_pkey; Type: CONSTRAINT; Schema: public; Owner: quickbyte_user
--

ALTER TABLE ONLY public.food_addons
    ADD CONSTRAINT food_addons_pkey PRIMARY KEY (id);


--
-- Name: food_images food_images_pkey; Type: CONSTRAINT; Schema: public; Owner: quickbyte_user
--

ALTER TABLE ONLY public.food_images
    ADD CONSTRAINT food_images_pkey PRIMARY KEY (id);


--
-- Name: food_variants food_variants_pkey; Type: CONSTRAINT; Schema: public; Owner: quickbyte_user
--

ALTER TABLE ONLY public.food_variants
    ADD CONSTRAINT food_variants_pkey PRIMARY KEY (id);


--
-- Name: foods foods_pkey; Type: CONSTRAINT; Schema: public; Owner: quickbyte_user
--

ALTER TABLE ONLY public.foods
    ADD CONSTRAINT foods_pkey PRIMARY KEY (id);


--
-- Name: order_addresses order_addresses_pkey; Type: CONSTRAINT; Schema: public; Owner: quickbyte_user
--

ALTER TABLE ONLY public.order_addresses
    ADD CONSTRAINT order_addresses_pkey PRIMARY KEY (id);


--
-- Name: order_items order_items_pkey; Type: CONSTRAINT; Schema: public; Owner: quickbyte_user
--

ALTER TABLE ONLY public.order_items
    ADD CONSTRAINT order_items_pkey PRIMARY KEY (id);


--
-- Name: orders orders_pkey; Type: CONSTRAINT; Schema: public; Owner: quickbyte_user
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_pkey PRIMARY KEY (id);


--
-- Name: otp_verifications otp_verifications_pkey; Type: CONSTRAINT; Schema: public; Owner: quickbyte_user
--

ALTER TABLE ONLY public.otp_verifications
    ADD CONSTRAINT otp_verifications_pkey PRIMARY KEY (id);


--
-- Name: payments payments_pkey; Type: CONSTRAINT; Schema: public; Owner: quickbyte_user
--

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT payments_pkey PRIMARY KEY (id);


--
-- Name: refresh_tokens refresh_tokens_pkey; Type: CONSTRAINT; Schema: public; Owner: quickbyte_user
--

ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT refresh_tokens_pkey PRIMARY KEY (id);


--
-- Name: restaurant_addresses restaurant_addresses_pkey; Type: CONSTRAINT; Schema: public; Owner: quickbyte_user
--

ALTER TABLE ONLY public.restaurant_addresses
    ADD CONSTRAINT restaurant_addresses_pkey PRIMARY KEY (id);


--
-- Name: restaurant_images restaurant_images_pkey; Type: CONSTRAINT; Schema: public; Owner: quickbyte_user
--

ALTER TABLE ONLY public.restaurant_images
    ADD CONSTRAINT restaurant_images_pkey PRIMARY KEY (id);


--
-- Name: restaurant_timings restaurant_timings_pkey; Type: CONSTRAINT; Schema: public; Owner: quickbyte_user
--

ALTER TABLE ONLY public.restaurant_timings
    ADD CONSTRAINT restaurant_timings_pkey PRIMARY KEY (id);


--
-- Name: restaurants restaurants_pkey; Type: CONSTRAINT; Schema: public; Owner: quickbyte_user
--

ALTER TABLE ONLY public.restaurants
    ADD CONSTRAINT restaurants_pkey PRIMARY KEY (id);


--
-- Name: reviews reviews_pkey; Type: CONSTRAINT; Schema: public; Owner: quickbyte_user
--

ALTER TABLE ONLY public.reviews
    ADD CONSTRAINT reviews_pkey PRIMARY KEY (id);


--
-- Name: delivery_partners uk4yd1b4sdfrpknxtpb1w4s42vo; Type: CONSTRAINT; Schema: public; Owner: quickbyte_user
--

ALTER TABLE ONLY public.delivery_partners
    ADD CONSTRAINT uk4yd1b4sdfrpknxtpb1w4s42vo UNIQUE (order_id);


--
-- Name: carts uk64t7ox312pqal3p7fg9o503c2; Type: CONSTRAINT; Schema: public; Owner: quickbyte_user
--

ALTER TABLE ONLY public.carts
    ADD CONSTRAINT uk64t7ox312pqal3p7fg9o503c2 UNIQUE (user_id);


--
-- Name: users uk6dotkott2kjsp8vw4d0m25fb7; Type: CONSTRAINT; Schema: public; Owner: quickbyte_user
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);


--
-- Name: refresh_tokens uk7tdcd6ab5wsgoudnvj7xf1b7l; Type: CONSTRAINT; Schema: public; Owner: quickbyte_user
--

ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT uk7tdcd6ab5wsgoudnvj7xf1b7l UNIQUE (user_id);


--
-- Name: payments uk8vo36cen604as7etdfwmyjsxt; Type: CONSTRAINT; Schema: public; Owner: quickbyte_user
--

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT uk8vo36cen604as7etdfwmyjsxt UNIQUE (order_id);


--
-- Name: users uk9q63snka3mdh91as4io72espi; Type: CONSTRAINT; Schema: public; Owner: quickbyte_user
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk9q63snka3mdh91as4io72espi UNIQUE (phone_number);


--
-- Name: categories uk_restaurant_category_name; Type: CONSTRAINT; Schema: public; Owner: quickbyte_user
--

ALTER TABLE ONLY public.categories
    ADD CONSTRAINT uk_restaurant_category_name UNIQUE (restaurant_id, name);


--
-- Name: order_addresses ukedthsvh7scpmbox9mow64ymoc; Type: CONSTRAINT; Schema: public; Owner: quickbyte_user
--

ALTER TABLE ONLY public.order_addresses
    ADD CONSTRAINT ukedthsvh7scpmbox9mow64ymoc UNIQUE (order_id);


--
-- Name: coupons ukf1u99ssbdsqass9ntq968codg; Type: CONSTRAINT; Schema: public; Owner: quickbyte_user
--

ALTER TABLE ONLY public.coupons
    ADD CONSTRAINT ukf1u99ssbdsqass9ntq968codg UNIQUE (coupon_code);


--
-- Name: restaurants ukfe6aq2gbudopv20yl6b77798m; Type: CONSTRAINT; Schema: public; Owner: quickbyte_user
--

ALTER TABLE ONLY public.restaurants
    ADD CONSTRAINT ukfe6aq2gbudopv20yl6b77798m UNIQUE (email);


--
-- Name: refresh_tokens ukghpmfn23vmxfu3spu3lfg4r2d; Type: CONSTRAINT; Schema: public; Owner: quickbyte_user
--

ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT ukghpmfn23vmxfu3spu3lfg4r2d UNIQUE (token);


--
-- Name: restaurant_addresses uko0g110077f6etph8jgvodukm9; Type: CONSTRAINT; Schema: public; Owner: quickbyte_user
--

ALTER TABLE ONLY public.restaurant_addresses
    ADD CONSTRAINT uko0g110077f6etph8jgvodukm9 UNIQUE (restaurant_id);


--
-- Name: delivery_partners ukrv2gnx8yoe0qh1meq1q915v57; Type: CONSTRAINT; Schema: public; Owner: quickbyte_user
--

ALTER TABLE ONLY public.delivery_partners
    ADD CONSTRAINT ukrv2gnx8yoe0qh1meq1q915v57 UNIQUE (phone_number);


--
-- Name: restaurants ukthig4i0d3mocamrqyupicmm61; Type: CONSTRAINT; Schema: public; Owner: quickbyte_user
--

ALTER TABLE ONLY public.restaurants
    ADD CONSTRAINT ukthig4i0d3mocamrqyupicmm61 UNIQUE (phone_number);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: quickbyte_user
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: cart_addons fk12j27gbkc58daj24b7jfapbks; Type: FK CONSTRAINT; Schema: public; Owner: quickbyte_user
--

ALTER TABLE ONLY public.cart_addons
    ADD CONSTRAINT fk12j27gbkc58daj24b7jfapbks FOREIGN KEY (food_addon_id) REFERENCES public.food_addons(id);


--
-- Name: order_items fk1huo7mby94sw84wam6xbfaex2; Type: FK CONSTRAINT; Schema: public; Owner: quickbyte_user
--

ALTER TABLE ONLY public.order_items
    ADD CONSTRAINT fk1huo7mby94sw84wam6xbfaex2 FOREIGN KEY (food_id) REFERENCES public.foods(id);


--
-- Name: refresh_tokens fk1lih5y2npsf8u5o3vhdb9y0os; Type: FK CONSTRAINT; Schema: public; Owner: quickbyte_user
--

ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT fk1lih5y2npsf8u5o3vhdb9y0os FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: orders fk2m9qulf12xm537bku3jnrrbup; Type: FK CONSTRAINT; Schema: public; Owner: quickbyte_user
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT fk2m9qulf12xm537bku3jnrrbup FOREIGN KEY (restaurant_id) REFERENCES public.restaurants(id);


--
-- Name: order_addresses fk50ktlegmhrk0yuibum1sg0jb8; Type: FK CONSTRAINT; Schema: public; Owner: quickbyte_user
--

ALTER TABLE ONLY public.order_addresses
    ADD CONSTRAINT fk50ktlegmhrk0yuibum1sg0jb8 FOREIGN KEY (order_id) REFERENCES public.orders(id);


--
-- Name: cart_addons fk57n9ao6mn7dvqpfjflb7g5d2d; Type: FK CONSTRAINT; Schema: public; Owner: quickbyte_user
--

ALTER TABLE ONLY public.cart_addons
    ADD CONSTRAINT fk57n9ao6mn7dvqpfjflb7g5d2d FOREIGN KEY (cart_item_id) REFERENCES public.cart_items(id);


--
-- Name: restaurant_images fk714rhrkn3odt4ucjohgipd9h4; Type: FK CONSTRAINT; Schema: public; Owner: quickbyte_user
--

ALTER TABLE ONLY public.restaurant_images
    ADD CONSTRAINT fk714rhrkn3odt4ucjohgipd9h4 FOREIGN KEY (restaurant_id) REFERENCES public.restaurants(id);


--
-- Name: payments fk81gagumt0r8y3rmudcgpbk42l; Type: FK CONSTRAINT; Schema: public; Owner: quickbyte_user
--

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT fk81gagumt0r8y3rmudcgpbk42l FOREIGN KEY (order_id) REFERENCES public.orders(id);


--
-- Name: reviews fk81nkg9op14w8c6hw7f25f029i; Type: FK CONSTRAINT; Schema: public; Owner: quickbyte_user
--

ALTER TABLE ONLY public.reviews
    ADD CONSTRAINT fk81nkg9op14w8c6hw7f25f029i FOREIGN KEY (food_id) REFERENCES public.foods(id);


--
-- Name: carts fkb5o626f86h46m4s7ms6ginnop; Type: FK CONSTRAINT; Schema: public; Owner: quickbyte_user
--

ALTER TABLE ONLY public.carts
    ADD CONSTRAINT fkb5o626f86h46m4s7ms6ginnop FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: order_items fkbioxgbv59vetrxe0ejfubep1w; Type: FK CONSTRAINT; Schema: public; Owner: quickbyte_user
--

ALTER TABLE ONLY public.order_items
    ADD CONSTRAINT fkbioxgbv59vetrxe0ejfubep1w FOREIGN KEY (order_id) REFERENCES public.orders(id);


--
-- Name: order_items fkc88ktaflukk5eyus11643ptwg; Type: FK CONSTRAINT; Schema: public; Owner: quickbyte_user
--

ALTER TABLE ONLY public.order_items
    ADD CONSTRAINT fkc88ktaflukk5eyus11643ptwg FOREIGN KEY (variant_id) REFERENCES public.food_variants(id);


--
-- Name: food_images fkcjvuyg5u6bluono3r4ppr9dd; Type: FK CONSTRAINT; Schema: public; Owner: quickbyte_user
--

ALTER TABLE ONLY public.food_images
    ADD CONSTRAINT fkcjvuyg5u6bluono3r4ppr9dd FOREIGN KEY (food_id) REFERENCES public.foods(id);


--
-- Name: delivery_partners fkdq84m5ew4x8y4vf8x0up0cv5k; Type: FK CONSTRAINT; Schema: public; Owner: quickbyte_user
--

ALTER TABLE ONLY public.delivery_partners
    ADD CONSTRAINT fkdq84m5ew4x8y4vf8x0up0cv5k FOREIGN KEY (order_id) REFERENCES public.orders(id);


--
-- Name: food_addons fke0wyldr8v1ha4htbempo9jmam; Type: FK CONSTRAINT; Schema: public; Owner: quickbyte_user
--

ALTER TABLE ONLY public.food_addons
    ADD CONSTRAINT fke0wyldr8v1ha4htbempo9jmam FOREIGN KEY (food_id) REFERENCES public.foods(id);


--
-- Name: restaurant_timings fkfg6vmjs5l0c58p1egiurunxn5; Type: FK CONSTRAINT; Schema: public; Owner: quickbyte_user
--

ALTER TABLE ONLY public.restaurant_timings
    ADD CONSTRAINT fkfg6vmjs5l0c58p1egiurunxn5 FOREIGN KEY (restaurant_id) REFERENCES public.restaurants(id);


--
-- Name: cart_items fkfgj1vb0wkn2gf7iowbxsgon5h; Type: FK CONSTRAINT; Schema: public; Owner: quickbyte_user
--

ALTER TABLE ONLY public.cart_items
    ADD CONSTRAINT fkfgj1vb0wkn2gf7iowbxsgon5h FOREIGN KEY (food_id) REFERENCES public.foods(id);


--
-- Name: cart_items fkkl22rt6va2briywtf9w0ih3ag; Type: FK CONSTRAINT; Schema: public; Owner: quickbyte_user
--

ALTER TABLE ONLY public.cart_items
    ADD CONSTRAINT fkkl22rt6va2briywtf9w0ih3ag FOREIGN KEY (variant_id) REFERENCES public.food_variants(id);


--
-- Name: reviews fkkquncb1glvrldaui8v52xfd5q; Type: FK CONSTRAINT; Schema: public; Owner: quickbyte_user
--

ALTER TABLE ONLY public.reviews
    ADD CONSTRAINT fkkquncb1glvrldaui8v52xfd5q FOREIGN KEY (customer_id) REFERENCES public.users(id);


--
-- Name: restaurants fkp5mmmypepihvmkdb83qwugr4d; Type: FK CONSTRAINT; Schema: public; Owner: quickbyte_user
--

ALTER TABLE ONLY public.restaurants
    ADD CONSTRAINT fkp5mmmypepihvmkdb83qwugr4d FOREIGN KEY (owner_id) REFERENCES public.users(id);


--
-- Name: foods fkpaltlojk6ds73o9vn3f2ri9gk; Type: FK CONSTRAINT; Schema: public; Owner: quickbyte_user
--

ALTER TABLE ONLY public.foods
    ADD CONSTRAINT fkpaltlojk6ds73o9vn3f2ri9gk FOREIGN KEY (category_id) REFERENCES public.categories(id);


--
-- Name: cart_items fkpcttvuq4mxppo8sxggjtn5i2c; Type: FK CONSTRAINT; Schema: public; Owner: quickbyte_user
--

ALTER TABLE ONLY public.cart_items
    ADD CONSTRAINT fkpcttvuq4mxppo8sxggjtn5i2c FOREIGN KEY (cart_id) REFERENCES public.carts(id);


--
-- Name: food_variants fkq6e6j4ro2j2h312xqbksvx0jq; Type: FK CONSTRAINT; Schema: public; Owner: quickbyte_user
--

ALTER TABLE ONLY public.food_variants
    ADD CONSTRAINT fkq6e6j4ro2j2h312xqbksvx0jq FOREIGN KEY (food_id) REFERENCES public.foods(id);


--
-- Name: orders fksjfs85qf6vmcurlx43cnc16gy; Type: FK CONSTRAINT; Schema: public; Owner: quickbyte_user
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT fksjfs85qf6vmcurlx43cnc16gy FOREIGN KEY (customer_id) REFERENCES public.users(id);


--
-- Name: reviews fksu8ow2q842enesfbqphjrfi5g; Type: FK CONSTRAINT; Schema: public; Owner: quickbyte_user
--

ALTER TABLE ONLY public.reviews
    ADD CONSTRAINT fksu8ow2q842enesfbqphjrfi5g FOREIGN KEY (restaurant_id) REFERENCES public.restaurants(id);


--
-- Name: restaurant_addresses fkt93ogkj8tqmttp8tq2af8iyi3; Type: FK CONSTRAINT; Schema: public; Owner: quickbyte_user
--

ALTER TABLE ONLY public.restaurant_addresses
    ADD CONSTRAINT fkt93ogkj8tqmttp8tq2af8iyi3 FOREIGN KEY (restaurant_id) REFERENCES public.restaurants(id);


--
-- Name: categories fktdst21nbth66utu5rvifn5x4a; Type: FK CONSTRAINT; Schema: public; Owner: quickbyte_user
--

ALTER TABLE ONLY public.categories
    ADD CONSTRAINT fktdst21nbth66utu5rvifn5x4a FOREIGN KEY (restaurant_id) REFERENCES public.restaurants(id);


--
-- PostgreSQL database dump complete
--

\unrestrict gzY25JSVZZ7IeRIopAthcQ3sNnnPnK0uOpbHi3ZkaTt7B8y65MaVL1UekLc1gm8

